name: flutter_rodrigo_manguinho
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  faker: ^2.0.0
  flutter:
    sdk: flutter
  http: ^0.13.4
  mockito: any
  mocktail: any
  test: any

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
